; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Getränkeautomat"
#define MyAppVersion "1.0"
#define MyAppPublisher "SMC IT AG"
#define MyAppURL "https://www.smc-it.de/"
#define MyAppExeName "Grafische Automatoberflaeche.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{56ACF155-2D49-4A79-BBFB-08FC7617756E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\Getraenkeautomat
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=mysetup-Getraenkeautomat
Compression=lzma
SolidCompression=yes
WizardStyle=modern
SetupIconFile=..\..\..\Documents\Visual Studio 2019\Code Snippets\javaScript\Logo\SMCIcon.ico

[Languages]
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "arabic"; MessagesFile: "compiler:Languages\German.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Siyamend\Desktop\Getränkautomat\Grafische Automatoberflaeche\bin\Debug\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name:..\..\..\Documents\Visual Studio 2019\Code Snippets\javaScript\Logo\SMCIcon.ico
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

